export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const ErrorINIT = "ErrorINIT";

// 読み込み中
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";

// チャット用タイプ
export const ADD_MESSAGE = "ADD_MESSAGE";
export const SET_MESSAGES = "SET_MESSAGES";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";

// プロフィール編集
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";
export const CHANGE_PROFILE_FALSE = "CHANGE_PROFILE_FALSE";

// 記事
export const POST_ARTICLE_SUCCESS = "POST_ARTICLE_SUCCESS";
export const POST_ARTICLE_FAIL = "POST_ARTICLE_FAIL";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_FAIL = "EDIT_ARTICLE_FAIL";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL";

// 記事関係 読み込み中
export const SET_ARTICLE_LOADING = "SET_ARTICLE_LOADING";
export const REMOVE_ARTICLE_LOADING = "REMOVE_ARTICLE_LOADING";

// ポートフォリオ
export const POST_PORTFOLIO_SUCCESS = "POST_PORTFOLIO_SUCCESS";
export const POST_PORTFOLIO_FAIL = "POST_PORTFOLIO_FAIL";
export const EDIT_PORTFOLIO_SUCCESS = "EDIT_PORTFOLIO_SUCCESS";
export const EDIT_PORTFOLIO_FAIL = "EDIT_PORTFOLIO_FAIL";
export const DELETE_PORTFOLIO_SUCCESS = "DELETE_PORTFOLIO_SUCCESS";
export const DELETE_PORTFOLIO_FAIL = "DELETE_PORTFOLIO_FAIL";
// ポートフォリオ関係 読み込み中
export const SET_PORTFOLIO_LOADING = "SET_PORTFOLIO_LOADING";
export const REMOVE_PORTFOLIO_LOADING = "REMOVE_PORTFOLIO_LOADING";

// 質問
export const POST_QUESTION_SUCCESS = "POST_QUESTION_SUCCESS";
export const POST_QUESTION_FAIL = "POST_QUESTION_FAIL";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";
// 質問関係 読み込み中
export const SET_QUESTION_LOADING = "SET_QUESTION_LOADING";
export const REMOVE_QUESTION_LOADING = "REMOVE_QUESTION_LOADING";

// コメント
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
// 質問関係 読み込み中
export const SET_COMMENT_LOADING = "SET_COMMENT_LOADING";
export const REMOVE_COMMENT_LOADING = "REMOVE_COMMENT_LOADING";
