export const languageData = [
  { id: "1", label: "Python" },
  { id: "2", label: "PHP" },
  { id: "3", label: "Ruby" },
  { id: "4", label: "JavaScript" },
  { id: "5", label: "SQL" },
  { id: "6", label: "HTML・CSS" },
  { id: "7", label: "C" },
  { id: "8", label: "C++" },
  { id: "9", label: "C#" },
  { id: "10", label: "Java" },
  { id: "11", label: "Kotlin" },
  { id: "12", label: "Objective-C" },
  { id: "13", label: "Swift" },
  { id: "14", label: "Go" },
  { id: "15", label: "Scala" },
  { id: "16", label: "R" },
  { id: "17", label: "Rust" },
  { id: "18", label: "Dart" },
];
